[#214] SharedBundleBox 구현 v1.1.0
Team-kiwing/Team-3seco-kiwing-fe pull request #230
Opened 2024-03-07 02:19 UTC by pkb9239

# 📝작업 내용
SharedBundleBox 컴포넌트를 구현하였습니다.
# 📷스크린샷(필요 시)

# ✨PR Point
- SharedBundleBox에 API를 연동하였습니다.
- `useCreateQuestionsToBundle` 선택한 질문을 꾸러미에 추가하는 훅을 구현했습니다.
- `useGetMyBundles` 내 꾸러미 목록을 가져오는 훅을 구현했습니다.
- 기존의 dropdown 컴포넌트의 체크모드는 선택한 모든 꾸러미에 질문을 추가할수있었는데 API자체가 하나의 꾸러미에만 질문을 추가할수있어서 일단은 그렇게 로직을 바꿔두었습니다.

2024-03-08 01:23 UTC, SoJuSo approved these changes
확인했습니다 고생하셨어요!

2024-03-08 01:23 UTC, SoJuSo commented on src/components/common/QuestionBox/QuestionBox.tsx
> +            {answer === null && '비공개 된 답변입니다.'}
추후 answerShareType으로 구분해주세요~!

2024-03-08 01:23 UTC, SoJuSo commented on src/components/SharedBundle/SharedBundleBox/SharedBundleBox.tsx
> +  const BUNDLE_BOX_OPTIONS =
요것도 뭔가 사용되는 곳이 많아서 추후에 리팩토링할때 훅으로 빼도 될 것 같네요

2024-03-08 02:36 UTC, SoJuSo requested changes

2024-03-08 02:36 UTC, SoJuSo commented on src/components/SharedBundle/SharedBundleBox/SharedBundleBox.tsx
>            <Button
P1; 경빈님 이거 SharedItemPage쪽이랑 같이 보셔야 할 것 같아요...!
요기서 버튼 형태로 구현되고 하위 속성인 드롭다운에도 button태그가 있어서 에러가 납니다..!!

이 사태를 어찌하면 좋을까요,,,
![image](https://github.com/Team-kiwing/Team-3seco-kiwing-fe/assets/90549862/52e6f499-d013-454a-9941-62991729f7bc)

2024-03-08 14:13 UTC, JaeHyunGround approved these changes
확인했습니다 !!

2024-03-08 14:21 UTC, SoJuSo commented on src/components/SharedBundle/SharedBundleBox/SharedBundleBox.tsx
>            <Button
확인했습니다~!

2024-03-08 14:21 UTC, SoJuSo approved these changes

2024-03-09 17:38 UTC, kim-hyunjoo approved these changes
고생하셨습니다!
저희 다중 리스트에 넣을 수 있도록 바뀌었으니 그 부분만 다시 반영하면 되겠네요~!

2024-03-09 17:38 UTC, kim-hyunjoo commented on src/components/SharedBundle/SharedBundleBox/SharedBundleBox.tsx
> +      setCheckedQuestionId([...checkedQuestionId, id]);
오 조금 더 명시적으로 바꿔주셔서 좋네요 ㅎㅎ

2024-03-10 07:59 UTC, merged